### PR TITLE
2438 data curation ddl format

### LINKED ISSUE #2438: Formatting for Data Curation Tools tabs
is there a better way to group the tools under the 'Data Curation' tab?

Suggestion:
Can group by 'Products'

- Upload predicted PUCs
- bulk assign PUCs
- bulk remove PUCs
- convert automatic PUCs
- resolve PUC conflicts
- bulk assign raw category
- bulk assign products to attributes

another group for "Chemicals"

- Chemical curation
- duplicate chemical records
- curated chemical removal

and maybe a group for 'Delete Data'

- delete extracted text
- removed cleaned composition data

that leaves:

- functional use curation
- LP keywords
- bulk document processing
- and Data group tracking (i think this could move under the "Data Sources" tab)

### PR DESCRIPTION
**Pull request by hausman-gdit**
Closes #2438 On jira

Change drop down formatting. Update deprecated selenium methods.

### Changes:
- added icons, rearranged  "Data Curation" & "QA" menu dropdowns
- update `find_element_by_foo("bar")` to `find_element(By.FOO, "bar")`

### CODE REVIEW

**Review by leogi22 — APPROVED** [review]
find_document_by_xxx depreciated since selenium 4 (we're using selenium 5) but still backward compatible. Leaves the other errors in integration tests

**Comment by hausman-gdit** [comment]
> find_document_by_xxx depreciated since selenium 4 (we're using selenium 5) but still backward compatible. Leaves the other errors in integration tests

the selenium version in `requirements.txt` is `4.5.0`. 

@leogi22  are you saying you got no failures for `find_element_by_FOO` (not `find_document_by`)?  Every single instance of `find_element_by_FOO` failed for me. These pass post update.

image
https://github.com/SeleniumHQ/selenium/blob/a4995e2c096239b42c373f26498a6c9bb4f2b3e7/py/CHANGES
> Selenium 4.3.0
* Deprecated find_element_by_* and find_elements_by_* are now removed (#10712)
* Deprecated Opera support has been removed (#10630)
* Fully upgraded from python 2x to 3.7 syntax and features (#10647)
* Added a devtools version fallback mechanism to look for an older version when mismatch occurs (#10749)
* Better support for co-operative multi inheritance by utilising super() throughout
* Improved type hints throughout


Also from the selenium docs
https://www.selenium.dev/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html?highlight=find_element#selenium.webdriver.remote.webdriver.WebDriver.find_element

**Comment by leogi22** [comment]
I guess the tests I looked at must have errors outside of the selenium upgrade suggested. Wondering what upgraded selenium (the bot?)
So Yes, find_element_by_blablabla no longer works! Thank you selenium for wasting our time! A cleaning freak must be at the command!

**Comment by hausman-gdit** [comment]
Haha I was like "oh nooo, whats wrong with the tests again!?".  I could have sworn that I'd rebuild my venv since we pinned the versions in `requirements` but oh well, glad theyre working now

**Pull request merged**
