### PR TITLE
1595: pared down Factotum landing page

### PR DESCRIPTION
**Pull request by fang-yan-csra**
1. Added Statistics and Visualization on the top menu bar.
2. Moved elements from landing page to those new pages.
3. Moved some test cases out to own file for clearer structure.
4. Added a migration which seems left from previous commits (only product fields verbose name changes).

### CODE REVIEW

**Comment by mwfrost** [comment]
closes #1595 

- [ ] New page 'statistics' exists, which includes the tables of statistics currently on the home page (both the 2x3 grid, and the table of statistics by group type)
- [ ] New page 'visualizations' exists, which includes the PUC tree diagram, bubble plots, and Venn diagram currently on the home page
 
Home page (Factotum.epa.gov) should display
- [ ] The 2x3 grid of basic numbers/statistics currently at the top of the home page
- [ ] A hyperlink to 'Get Data', linking to https://factotum.epa.gov/get_data/
- [ ] A hyperlink to 'Statistics' linking to the new statistics page
- [ ] A hyperlink to 'Visualizations,' which links to the new visualizations page

**Comment by mwfrost** [comment]
@fang-yan-csra according to the #1595 ticket, the Statistics page should include a duplicate copy of the 2x3 grid of stats from the home page. Will you have time to add that before the sprint review deadline?

**Comment by fang-yan-csra** [comment]
> @fang-yan-csra according to the #1595 ticket, the Statistics page should include a duplicate copy of the 2x3 grid of stats from the home page. Will you have time to add that before the sprint review deadline?

Ah, didn't realize need to duplicate the grid. I'll work on it.

**Comment by fang-yan-csra** [comment]
Matt's commit to include the Grid in Statistics looks good. Thanks!

**Pull request merged**
