### PR TITLE
keep logstash container running

### PR DESCRIPTION
**Pull request by fang-yan-csra**
Changed the logstash server restart from "no" to unless-stopped, as the logstash container has scheduled nightly job now. Also added DELETE_INDEX_SCHEDULE and REINDEX_SCHEDULE environmental variables to customized the scheduled time. Defaults to 1:25AM and 1:30AM daily.

### CODE REVIEW

**Comment by mcovalt** [comment]
We're going to have to think about how we'll implement this in our development environments. There needs to be some way for us to load the fixtures data on-demand.

**Comment by fang-yan-csra** [comment]
> We're going to have to think about how we'll implement this in our development environments. There needs to be some way for us to load the fixtures data on-demand.

How about make the scheduled time configurable via environment variables? This way dev can schedule it in the next minute or so.

**Comment by mcovalt** [comment]
That seems like a great approach.

**Comment by fang-yan-csra** [comment]
I pushed to add the configuration. Thanks!

**Pull request merged**
