### PR TITLE
1282 Bubble Plot and Legend

### PR DESCRIPTION
**Pull request by mwfrost**
Closes: #1282 

Numerous changes all over the code, from the database to the django models to the D3 charts. 

Make sure to migrate - this branch brings in new database views for calculating the product count and the cumulative product count for each PUC, with and without a DTXSID filter applied. There is no longer any looping over Python objects - all the summaries are calculated in SQL. 

This change applies to both the Visualizations page and the Chemical Detail Page. 

Note that the Chemical Detail page can have a PUC in the URL, as specified in ticket #1377 . The page opens zoomed in on that PUC, with the legend expanded accordingly. But then the user is free to click around on other PUCs, so the URL becomes obsolete. As long as the page is meant to be a summary of the Chemical+PUC combination, this awkwardness is inevitable.

To test with the seed data, go to 

http://localhost:8000/visualizations/

and click on the PUC legend and the bubble chart. The two elements should be in sync. 

http://localhost:8000/chemical/DTXSID9022528/puc/186/

### CODE REVIEW

**Comment by mwfrost** [comment]
The rendering of the bubble plots is still very slow with production data. The unfortunate structure of `gen_cat -> prod_fam -> prod_type` requires a `UNION` query to stitch together all the cumulative counts in SQL. The SQL views help, but it's still too expensive for my comfort. The next step in paying down this technical debt might be to implement caching somewhere along the way.

**Comment by mwfrost** [comment]
There are two new migrations in this branch. One of them changes the MySQL view that was build to select the uberpuc for each product. That uberpuc is now stored as an attribute on the `ProductToPUC` model, and the view was changed to select from that field.

**Comment by mwfrost** [comment]
This branch now uses the `django-cacheops` package to cache the Chemical Detail Page data into the redis key-value store. Run `pip install -r requirements.txt` before restarting your local server.

The caching happens at the DTXSID level, so each new chemical that's loaded can take up to thirty seconds (on current prod data). Subsequent page loads, though, use the cached version.

**Review by fang-yan-csra — APPROVED** [review]
1. Verified the puc table and bubble plot navigation are synced.
2. The chemical page initial load is slow, but consequent load is fast as queryset is cached.

**Pull request merged**
