### PR TITLE
529 Refine QA page

### PR DESCRIPTION
**Pull request by mwfrost**
I am ready for someone with a few spare minutes to check out my QA page redesign, specified in ticket #529 

Here are the three requirements specified in the ticket:
- Make 'extracted text info' box only editable when 'edit composition records' button is on (this is same functionality as the 'extracted chemical' info, which is only editable when 'edit composition records' button is on. [*NOTE:* after discussion with Kathie, the ability to edit the ExtractedText record was moved into a modal form. The "Edit" button on the detail record formset only applies to those detail records.]
- 'Save edits' button should only be visible/enabled when the 'edit composition records' button is 'on'
- In the header box, allow user to change the Document Type (however only document types allowed are those which are children of the data group type to which the document belongs)

The formset is tricky to display, since the number of forms per child record can vary from 2 in the case of a CPCat document up to 11 in the case of a Composition record. The long text fields in the HHR documents are especially troublesome to lay out.

Every four fields, the template adds a new row. That increment can be changed.

*Composition* example: `/qa/extractedtext/7/`
*ExtractedHHDoc* example: `/qa/extractedtext/354783/`
*List Presence* example: `/qa/extractedtext/254781/`
*Functional Use* example: `/qa/extractedtext/5/`

I have removed the curated fields (True CAS, True Chem Name, and SID) from the QA display.

The formset uses a table for layout, and you will see a row above each record with some dummy code declaring its CSS selector ID. I've used the RawChem id value as a key here, thinking it might help us with testing and styling.

### CODE REVIEW

**Comment by mwfrost** [comment]
Please use data document 7 to confirm that the curated fields have been removed from the QA display, as requested in #736

**Comment by mwfrost** [comment]
Styling the error messages deserves a ticket of its own.

**Comment by zachmunzenrider** [comment]
I'm fine with that. Do you mind making the other change?

**Comment by mwfrost** [comment]
The button stye has been changed.

**Pull request closed without merging**
