### PR TITLE
823 ability to store document sub-title

### LINKED ISSUE #823: ability to store document sub-title
As a Factotum data curator 
I would like to store a sub-title for a data document
So that I can store the table name in addition to the document title

Currently, the document title is stored in dashboard_datadocument.title

We also have a need to store a 'sub-title' for each document.

Definition of Done:
1. From the data document page (http://factotum.epa.gov/datadocument/1372072/), ability to enter a data document sub title.
2. data document sub title should appear in the 'header' portion of the page, as the first entry (i.e. before data source)
3. data document sub title is max 250 characters, and is not required (is allowed to be null)

Implement editing functionality to build on #746

### PR DESCRIPTION
**Pull request by mcovalt**
This continues the behavior of setting a `NULL` for string-based fields, but take a look at the [Django docs on this](https://docs.djangoproject.com/en/2.2/ref/models/fields/#null):

> Avoid using `null` on string-based fields such as `CharField` and `TextField`. If a string-based field has `null=True`, that means it has two possible values for “no data”: `NULL`, and the empty string. In most cases, it’s redundant to have two possible values for “no data;” the Django convention is to use the empty string, not `NULL`.

Closes #823

### CODE REVIEW

**Comment by mwfrost** [comment]
Would it be smart to set a default of `""` on this field?

**Comment by mcovalt** [comment]
Ultimately I think so. The reason I chose `default=None` here is because I wanted to continue whatever trend is used in the production database which I assume is string "no data" being `NULL`.

Maybe this is a good PR for a more intrusive commit? Where models are normalized with string "no data" being `""` and `blank=True null=False`?

**Comment by mwfrost** [comment]
The document_type form is causing trouble in the editing screen. 
This is an example from the prod database, where the document_type_id is 1 (Unidentified).

On the data document detail screen:
sc_2019423_121216_67

On the editing screen, the dropdown menu has not been populated with the Unidentified document type:
sc_2019423_121521_734

So when I try to save my edits, the form fails to validate:
sc_2019423_121636_722

Fixing this might be as simple as setting the `initial` attribute for the form.

**Comment by mwfrost** [comment]
Scratch that - initial isn't appropriate here. The problem is that the form is not bound to data when it's rendered. I think it's related to a problem I was having on another ticket

**Comment by mcovalt** [comment]
What is this `pk` so I can see what's going on here? 

The `document_type` choices are being filtered [in the form](https://github.com/HumanExposure/factotum/blob/878c5056f6f4692846f661b14603cec83f9c0f33/dashboard/forms.py#L402-L404) in order to adhere to the [`DataDocument.clean()` validation](https://github.com/HumanExposure/factotum/blob/878c5056f6f4692846f661b14603cec83f9c0f33/dashboard/models/data_document.py#L103-L110). I think this is more a problem with invalid seed data than the way the code works, but I could be wrong.

**Comment by mwfrost** [comment]
I'm using prod data, unfortunately

I haven't yet wiped it out and reloaded the seed data
pick any document in the seed data where the document_type_id is 1 and see if you can reproduce it

**Comment by mwfrost** [comment]
The problem turns out to be in how we are validating the document_type+group_type combination.
A data document with document_type of 1 (Unidentified) is only allowed to belong to a group of group_type 1 (Unidentified).
For a document in group_type 2 (Composition) to be Unidentified, it needs to use the document_type 2 (Unidentified).

The combination of document_type 1 and group_type 2 is not allowed to appear in the document_type dropdown's QuerySet, so it gives up and displays null. ("--------")

The seed data and production data both include documents with document_type 1 and group_type <> 1, so we need to implement a solution that does not break under these conditions. Proposal to allow document_type 1 in the menu's queryset no matter what the group_type is.

**Comment by mwfrost** [comment]
The hotfix works like it should, but the user now sees two rows in the dropdown for "Unidentified". If you add these lines to the end of forms.py, it will change the dropdown labels to include the group type:
```
        self.fields['document_type'].label_from_instance = self.label_from_instance

    @staticmethod
    def label_from_instance(obj):
        return f"{obj.title} (in Group Type: {obj.group_type})"
```

**Comment by mcovalt** [comment]
Repeating here so I can trigger a GitHub link...

Related to #637

**Pull request merged**
