### PR TITLE
1335 bubbleplot borders

### PR DESCRIPTION
**Pull request by BryanMG957**

### CODE REVIEW

**Review by fang-yan-csra — COMMENTED** [review]
Can we make the border color the same as the PUC group belongs to instead of all Black?

**Comment by BryanMG957** [comment]
> Can we make the border color the same as the PUC group belongs to instead of all Black?

Hey @fang-yan-csra Sakshi told me she wanted it black.

**Comment by BryanMG957** [comment]
Made the border 4px, 1px works for the main problem (level 3 puc that are alone outside a level 1/2 circle) but Sakshi still wanted it to be visible inside a level 2 puc @fang-yan-csra

**Comment by fang-yan-csra** [comment]
I'm fine with the change as the border color matches the puc group color now.

**Review by zachmunzenrider — APPROVED** [review]

**Pull request merged**
