### PR TITLE
2381 tech debt func test fixes

### LINKED ISSUE #2381: Update failing tests
This is a follow-up ticket to #2380.
More description will be added depending on results of that ticket.

To Do/Acceptance criteria:
- Investigate failing tests, and update them to current or mark them as legacy or no longer relevant, and remove.

### PR DESCRIPTION
**Pull request by hausman-gdit**
WIP Closes #2381 

`python manage.py test dashboard.tests.functional --exclude-tag=fails_in_suite`

### Changes:
- Create additional directories in `factotum` that are `.gitignored`
- when running tests in suite, add `--exclude-tag=fails_in_suite` 

mkdir
- assets/
- media/
- ? csv_storage/

Semi related note: 
`python manage.py runserver --insecure`
& `DEBUG=false`
& `MEDIA_*`  /  `STATIC_*`  `.env`

### CODE REVIEW

**Comment by hausman-gdit** [comment]
a - manage.py - init run (13)
b - manage.py - no change, one addt'l (14)
c - pytest - 18 failed, 278 passed, 5 warnings, 35 errors in 1533.16s (0:25:33)
d - nuke/pave, reindex, runserver & let sit for ~15 min
e - pytest - run by file, individually those failed
f - manage.py - post one epa template merge


|	filename	|	class	|	test	|	a	|	b	|	c	|	d	|	e	|	f	|
|	 ------------------------------	|	 ------------------------------	|	 ------------------------------	|	 ------------------------------	|	 ------------------------------	|	 ------------------------------	|	 ------------------------------	|	 ------------------------------	|	 ------------------------------	|
|	test_ajax	|	TestAjax	|	test_curated_chemicals	|	1	|	1	|	1	|	1	|		|	1	|
|	test_ajax	|	TestAjax	|	test_lp_tag_detail_filtered_by_tagset	|	1	|	1	|	1	|	1	|	X	|		|
|	test_auditlog	|	AuditLogTest	|	test_audit_log_presence_upload	|	1	|	1	|	1	|	1	|	0	|	1	|
|	test_dashboard	|	DashboardTest	|	test_grouptype_stats_table	|	1	|	1	|	1	|	1	|	1	|	1	|
|	test_dashboard	|	DashboardTestWithFixtures	|	test_chemical_card	|		|	1	|	1	|	1	|	1	|		|
|	test_dashboard	|	DashboardTestWithFixtures	|	test_producttopuc_counts	|	1	|	1	|	1	|		|	1	|	1	|
|	test_datadocument_detail	|	DataDocumentDetailTest	|	test_delete	|	1	|	1	|		|	1	|	0	|	1	|
|	test_datagroup_detail	|	DataGroupDetailTest	|	test_bulk_create_post	|		|		|	1	|		|	1	|		|
|	test_datagroup_detail	|	DataGroupDetailTest	|	test_bulk_create_products_form	|		|		|	1	|		|	1	|		|
|	test_datagroup_detail	|	DataGroupDetailTest	|	test_detail_table_media_document_link	|		|		|	1	|		|	1	|		|
|	test_datagroup_detail	|	DataGroupDetailTest	|	test_detail_table_puc_classification_method	|		|		|	1	|		|	1	|		|
|	test_datasource_index	|	DataSourceTestWithFixtures	|	test_detail_page	|		|		|		|		|		|	1	|
|	test_extracted_text_forms	|		|		|		|		|	1	|		|		|		|
|	test_extracted_text_upload	|	UploadExtractedFileTest	|	test_chemical_presence_upload	|	1	|	1	|		|	1	|		|	1	|
|	test_get_data	|	TestGetData	|	test_download_co	|		|		|		|		|		|		|
|	test_get_data	|	TestGetData	|	test_harmonized_media_detail_page	|		|		|		|		|		|		|
|	test_nav_bar	|	NavBarTest	|	test_data_curation	|		|		|		|		|		|	1	|
|	test_product_csv_upload	|	UploadProductTest	|	test_image_directory_exceeds_count_error	|	1	|	1	|	1	|	1	|	0	|	1	|
|	test_product_csv_upload	|	UploadProductTest	|	test_image_directory_too_large_error	|	1	|	1	|	1	|	1	|	0	|	1	|
|	test_product_csv_upload	|	UploadProductTest	|	test_image_file_too_large_error	|	1	|	1	|	1	|	1	|	0	|	1	|
|	test_product_csv_upload	|	UploadProductTest	|	test_valid_product_data_upload_with_image	|	1	|	1	|	1	|	1	|	0	|	1	|
|	test_product_detail	|	TestProductDetail	|	test_image_upload	|	1	|	1	|	1	|	1	|		|	1	|
|	test_rawcategory_to_puc_form	|		|		|		|		|	1	|		|		|		|
|	test_rawcategory_to_puc_view	|		|		|		|		|	1	|		|		|		|
|	test_root_url_no_login	|	RootUrlNoLoginTest	|	test_dashboard_login_not_required	|		|		|	1	|		|	0	|		|
|	test_root_url_no_login	|	RootUrlNoLoginTest	|	test_dashboard_news	|		|		|	1	|		|	0	|		|
|	test_root_url_no_login	|	RootUrlNoLoginTest	|	test_list_presence_tag_detail_login_not_required	|		|		|	1	|		|	0	|		|
|	test_root_url_no_login	|	RootUrlNoLoginTest	|	test_list_presence_tag_list_login_not_required	|		|		|	1	|		|	0	|		|
|	test_root_url_no_login	|	RootUrlNoLoginTest	|	test_puc_list_login_not_required	|		|		|	1	|		|	0	|		|
|	test_root_url_no_login	|	RootUrlNoLoginTest	|	test_root_url_resolves_to_index_view	|		|		|	1	|		|	0	|		|
|	test_search	|	TestSearch	|	test_boosted_fields	|		|		|		|		|		|		|
|	test_search	|	TestSearch	|	test_document_search_product_count	|		|		|		|		|		|		|
|	test_search	|	TestSearch	|	test_hero_id	|		|		|		|		|		|		|
|	test_search	|	TestSearch	|	test_input	|		|		|		|		|		|		|
|	test_search	|	TestSearch	|	test_model_counts	|		|		|		|		|		|		|
|	test_search	|	TestSearch	|	test_phrase_search	|	1	|	1	|	1	|	1	|		|	1	|
|	test_search	|	TestSearch	|	test_pmid	|		|		|		|		|		|		|
|	test_search	|	TestSearch	|	test_results_page	|		|		|		|		|		|		|
|	test_search	|	TestSearch	|	test_search_harmonized_media	|		|		|	1	|		|		|		|
|	test_search	|	TestSearch	|	test_search_tag	|		|		|		|		|		|		|
|	test_search	|	TestSearchView	|	test_special_char_search	|		|		|		|		|		|		|
|	test_dashboard	|	DashboardTest	|	test_public_navbar	|		|		|		|		|		|	1	|
|	test_nav_bar	|	NavBarTest	|	test_home_page_returns_correct_html	|		|		|		|		|		|	1	|
|	test_qa_summary	|	TestCleaningQASummary	|	test_qa_summary	|		|		|		|		|		|	1	|
|	test_qa_summary	|	TestFUQASummary	|	test_fu_qa_summary	|		|		|		|		|		|	1	|
|	test_qa_summary	|	TestFUQASummary	|	test_qa_summary	|		|		|		|		|		|	1	|
|	test_search	|	TestSearch	|	test_anonymous_read	|		|		|		|		|		|	1	|
|	test_auditlog	|	AuditLogTest	|	test_audit_log_chem_upload	|		|		|		|		|		|	1	|

**Comment by hausman-gdit** [comment]
@leogi22 How many functional tests are being run? You have zero fails/errors?

**Comment by leogi22** [comment]
1 Fail due to a missing zip file. All others pass

**Comment by leogi22** [comment]
Ran 331 tests in 2623.983s

FAILED (failures=1, errors=1)

**Comment by hausman-gdit** [comment]
> Ran 331 tests in 2623.983s
> 
> FAILED (failures=1, errors=1)

Darn, I'm having 6. One is the count mismatch again. I have `DISABLE_CACHE` enabled. I'll try reloading the db.
 the `test_audit_log_presence_upload` etc files with pathing issues are still failing, I'll fix those for me
 
 ```Ran 331 tests in 1578.636s FAILED (failures=6, errors=5)```

**Review by leogi22 — APPROVED** [review]

**Pull request merged**
