### PR TITLE
#687 add field, tweak admin, test

### PR DESCRIPTION
**Pull request by debboutr**
I've added to the admin a filter on `script_type` and for the list display I used a function to populate the confidence column for only `EX` Scripts, I like this, but I couldn't get this updated confidence column to be sortable like it would be if they were displayed for all types. Don't know how many scripts there are likely to be, but it seems okay for now

### CODE REVIEW

**Comment by mwfrost** [comment]
From the ticket: "Confidence level is a required field for every registered extraction script (can not be null)"

How should we enforce the conditionally required status of the new field? Shouldn't this field be assigned `Null=True` so that the download scripts can have `None` for their confidence levels?

Letting the validator police the form input might be the only way to manage this. We can't enforce `Null=False` at the database level, since all the download scripts are allowed to have `None` values.

**Comment by mwfrost** [comment]
Maybe download scripts have "100" confidence levels?

**Comment by mwfrost** [comment]
Can you export a new version of `04_PUC.yaml` with this new field in it?

**Comment by debboutr** [comment]
@mwfrost I will update the seed data. As for the nullification of the `confidence` field, I'm not sure how important it is that we have the `min/max` validators on this field, but that would be problematic if we wanted to have `null` for any script that isn't `'EX'`. I don like the implementation in the link you've put above, but as long as all of this table is where we are going to put this field it will have to hold _some_ value, whether that be `null` or `1` didn't seem like it would be much of a deal to @kdionisio when talking through this with her. There are certainly other ways to implement it. You've probably already noticed that  at leas in the `admin` panel I filter out the value for other type scripts in `confidence` column so at least visually it looks appropriate there.

**Comment by mwfrost** [comment]
If we can give download scripts a value of 1 or 100 or 0 or whatever without causing problems, then it's fine to leave the field non-nullable.

**Pull request merged**
